export const players = [
  {
    email: "khaled.jalloul@hotmail.com",
    phoneNumber: "+96103760943",
    hash: "hash123",
    firstName: "Khaled",
    lastName: "Jalloul",
    gender: "M",
    height: 180,
    weight: 75,
    age: 25,
    nationality: "Lebanon",
  },
  {
    email: "jane.doe@example.com",
    phoneNumber: "+96176095434",
    hash: "hash456",
    firstName: "Jane",
    lastName: "Doe",
    gender: "F",
    height: 170,
    weight: 60,
    age: 30,
    nationality: "Canada",
    position: "midfielder",
  },
];