version: '3.3'
services:
  nestjs-backend:
    image: fitchain-nestjs-backend
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - dev-db
      - test-db
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
volumes:
  postgres_data_dev:
  postgres_data_test: